import type { Client, Vehicle, Inspection, DashboardStats } from './types';

// ─── Clients ──────────────────────────────────────────────────────────────────
export const mockClients: Client[] = [
  {
    id: 'cli-001',
    name: 'PT. Berkah Transportasi Nusantara',
    contactPerson: 'Budi Santoso',
    phone: '0811-234-5678',
    email: 'budi.santoso@berkah-trans.co.id',
    address: 'Jl. Raya Pasar Minggu No. 15',
    city: 'Jakarta Selatan',
    totalVehicles: 4,
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'cli-002',
    name: 'CV. Armada Maju Bersama',
    contactPerson: 'Siti Rahayu',
    phone: '0812-345-6789',
    email: 'siti.rahayu@armadamaju.com',
    address: 'Jl. Asia Afrika No. 88',
    city: 'Bandung',
    totalVehicles: 3,
    status: 'active',
    createdAt: '2024-02-03',
  },
  {
    id: 'cli-003',
    name: 'UD. Kilat Express',
    contactPerson: 'Ahmad Fadli',
    phone: '0813-456-7890',
    email: 'ahmad.fadli@kilat-express.com',
    address: 'Jl. Rungkut Industri No. 24',
    city: 'Surabaya',
    totalVehicles: 5,
    status: 'active',
    createdAt: '2024-02-20',
  },
  {
    id: 'cli-004',
    name: 'Primavera Rent A Car',
    contactPerson: 'Dewi Puspita',
    phone: '0814-567-8901',
    email: 'dewi@primavera-rental.com',
    address: 'Jl. Bypass Ngurah Rai No. 300',
    city: 'Denpasar',
    totalVehicles: 8,
    status: 'active',
    createdAt: '2024-03-10',
  },
  {
    id: 'cli-005',
    name: 'PT. Logistik Cepat Indonesia',
    contactPerson: 'Reza Firmansyah',
    phone: '0815-678-9012',
    email: 'reza@logistik-cepat.id',
    address: 'Jl. Gatot Subroto No. 67',
    city: 'Medan',
    totalVehicles: 6,
    status: 'inactive',
    createdAt: '2024-03-25',
  },
  {
    id: 'cli-006',
    name: 'Blue Bird Taxi Unit 5',
    contactPerson: 'Hendra Wijaya',
    phone: '0816-789-0123',
    email: 'hendra.wijaya@bluebird.id',
    address: 'Jl. Mampang Prapatan No. 60',
    city: 'Jakarta Selatan',
    totalVehicles: 12,
    status: 'active',
    createdAt: '2024-04-08',
  },
  {
    id: 'cli-007',
    name: 'Wahana Auto Service',
    contactPerson: 'Rina Marlina',
    phone: '0817-890-1234',
    email: 'rina@wahana-auto.co.id',
    address: 'Jl. Solo-Jogja Km. 12',
    city: 'Yogyakarta',
    totalVehicles: 2,
    status: 'active',
    createdAt: '2024-05-01',
  },
  {
    id: 'cli-008',
    name: 'PT. Trans Nusa Cargo',
    contactPerson: 'Dimas Pratama',
    phone: '0818-901-2345',
    email: 'dimas.pratama@transnusa.com',
    address: 'Jl. Kaligawe Raya No. 99',
    city: 'Semarang',
    totalVehicles: 7,
    status: 'active',
    createdAt: '2024-05-15',
  },
];

// ─── Vehicles ─────────────────────────────────────────────────────────────────
export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-001',
    licensePlate: 'B 1234 ABC',
    brand: 'Toyota',
    model: 'Avanza',
    year: 2022,
    color: 'Putih',
    clientId: 'cli-001',
    clientName: 'PT. Berkah Transportasi Nusantara',
    status: 'active',
    lastInspection: '2024-07-10',
    totalInspections: 3,
    createdAt: '2024-01-20',
  },
  {
    id: 'veh-002',
    licensePlate: 'B 5678 DEF',
    brand: 'Honda',
    model: 'Brio',
    year: 2023,
    color: 'Silver',
    clientId: 'cli-001',
    clientName: 'PT. Berkah Transportasi Nusantara',
    status: 'active',
    lastInspection: '2024-07-15',
    totalInspections: 2,
    createdAt: '2024-01-22',
  },
  {
    id: 'veh-003',
    licensePlate: 'D 9012 GHI',
    brand: 'Daihatsu',
    model: 'Xenia',
    year: 2021,
    color: 'Abu-abu',
    clientId: 'cli-002',
    clientName: 'CV. Armada Maju Bersama',
    status: 'active',
    lastInspection: '2024-06-28',
    totalInspections: 4,
    createdAt: '2024-02-05',
  },
  {
    id: 'veh-004',
    licensePlate: 'L 3456 JKL',
    brand: 'Mitsubishi',
    model: 'Xpander',
    year: 2023,
    color: 'Hitam',
    clientId: 'cli-003',
    clientName: 'UD. Kilat Express',
    status: 'active',
    lastInspection: '2024-07-20',
    totalInspections: 1,
    createdAt: '2024-02-25',
  },
  {
    id: 'veh-005',
    licensePlate: 'DK 7890 MNO',
    brand: 'Toyota',
    model: 'Rush',
    year: 2022,
    color: 'Merah',
    clientId: 'cli-004',
    clientName: 'Primavera Rent A Car',
    status: 'active',
    lastInspection: '2024-07-18',
    totalInspections: 5,
    createdAt: '2024-03-12',
  },
  {
    id: 'veh-006',
    licensePlate: 'BK 1234 PQR',
    brand: 'Suzuki',
    model: 'Ertiga',
    year: 2023,
    color: 'Putih',
    clientId: 'cli-005',
    clientName: 'PT. Logistik Cepat Indonesia',
    status: 'inactive',
    lastInspection: '2024-05-30',
    totalInspections: 2,
    createdAt: '2024-03-28',
  },
  {
    id: 'veh-007',
    licensePlate: 'B 5678 STU',
    brand: 'Honda',
    model: 'Jazz',
    year: 2022,
    color: 'Biru',
    clientId: 'cli-006',
    clientName: 'Blue Bird Taxi Unit 5',
    status: 'active',
    lastInspection: '2024-07-22',
    totalInspections: 6,
    createdAt: '2024-04-10',
  },
  {
    id: 'veh-008',
    licensePlate: 'AB 9012 VWX',
    brand: 'Yamaha',
    model: 'NMAX',
    year: 2023,
    color: 'Hitam',
    clientId: 'cli-007',
    clientName: 'Wahana Auto Service',
    status: 'active',
    lastInspection: null,
    totalInspections: 0,
    createdAt: '2024-05-02',
  },
  {
    id: 'veh-009',
    licensePlate: 'H 3456 YZA',
    brand: 'Toyota',
    model: 'Kijang Innova',
    year: 2021,
    color: 'Silver',
    clientId: 'cli-008',
    clientName: 'PT. Trans Nusa Cargo',
    status: 'active',
    lastInspection: '2024-07-05',
    totalInspections: 3,
    createdAt: '2024-05-18',
  },
  {
    id: 'veh-010',
    licensePlate: 'B 7890 BCD',
    brand: 'Suzuki',
    model: 'Ignis',
    year: 2023,
    color: 'Orange',
    clientId: 'cli-006',
    clientName: 'Blue Bird Taxi Unit 5',
    status: 'active',
    lastInspection: '2024-07-12',
    totalInspections: 2,
    createdAt: '2024-04-12',
  },
  {
    id: 'veh-011',
    licensePlate: 'L 1234 EFG',
    brand: 'Hyundai',
    model: 'Ioniq 6',
    year: 2023,
    color: 'Putih',
    clientId: 'cli-003',
    clientName: 'UD. Kilat Express',
    status: 'active',
    lastInspection: '2024-07-19',
    totalInspections: 1,
    createdAt: '2024-02-28',
  },
  {
    id: 'veh-012',
    licensePlate: 'D 5678 HIJ',
    brand: 'Wuling',
    model: 'Air ev',
    year: 2023,
    color: 'Teal',
    clientId: 'cli-002',
    clientName: 'CV. Armada Maju Bersama',
    status: 'active',
    lastInspection: '2024-06-15',
    totalInspections: 2,
    createdAt: '2024-02-07',
  },
];

// ─── Inspections ──────────────────────────────────────────────────────────────
export const mockInspections: Inspection[] = [
  {
    id: 'ins-001',
    vehicleId: 'veh-007',
    licensePlate: 'B 5678 STU',
    vehicleName: 'Honda Jazz 2022',
    clientId: 'cli-006',
    clientName: 'Blue Bird Taxi Unit 5',
    inspectorName: 'Ahmad Rizki',
    status: 'completed',
    angles: [
      {
        angle: 'front',
        imageUrl: '/mock/front.jpg',
        resultUrl: '/mock/front-result.jpg',
        damages: [
          { id: 'd1', type: 'scratch', severity: 'low', confidence: 0.87, angle: 'front', x: 120, y: 80, width: 60, height: 20 },
          { id: 'd2', type: 'dent', severity: 'medium', confidence: 0.92, angle: 'front', x: 200, y: 150, width: 40, height: 35 },
        ],
        capturedAt: '2024-07-22T09:15:00Z',
      },
      {
        angle: 'rear',
        imageUrl: '/mock/rear.jpg',
        resultUrl: '/mock/rear-result.jpg',
        damages: [
          { id: 'd3', type: 'crack', severity: 'high', confidence: 0.95, angle: 'rear', x: 90, y: 60, width: 80, height: 30 },
        ],
        capturedAt: '2024-07-22T09:18:00Z',
      },
      {
        angle: 'left',
        imageUrl: '/mock/left.jpg',
        resultUrl: '/mock/left-result.jpg',
        damages: [],
        capturedAt: '2024-07-22T09:21:00Z',
      },
      {
        angle: 'right',
        imageUrl: '/mock/right.jpg',
        resultUrl: '/mock/right-result.jpg',
        damages: [
          { id: 'd4', type: 'scratch', severity: 'low', confidence: 0.78, angle: 'right', x: 160, y: 200, width: 50, height: 15 },
        ],
        capturedAt: '2024-07-22T09:24:00Z',
      },
    ],
    totalDamages: 4,
    notes: 'Kerusakan pada bagian belakang perlu segera diperbaiki.',
    startedAt: '2024-07-22T09:10:00Z',
    completedAt: '2024-07-22T09:30:00Z',
    createdAt: '2024-07-22',
  },
  {
    id: 'ins-002',
    vehicleId: 'veh-005',
    licensePlate: 'DK 7890 MNO',
    vehicleName: 'Toyota Rush 2022',
    clientId: 'cli-004',
    clientName: 'Primavera Rent A Car',
    inspectorName: 'Sari Dewi',
    status: 'completed',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: '/mock/front-result.jpg', damages: [{ id: 'd5', type: 'dent', severity: 'medium', confidence: 0.88, angle: 'front', x: 100, y: 100, width: 50, height: 40 }], capturedAt: '2024-07-18T14:00:00Z' },
      { angle: 'rear', imageUrl: '/mock/rear.jpg', resultUrl: '/mock/rear-result.jpg', damages: [], capturedAt: '2024-07-18T14:05:00Z' },
      { angle: 'left', imageUrl: '/mock/left.jpg', resultUrl: '/mock/left-result.jpg', damages: [{ id: 'd6', type: 'tire_flat', severity: 'high', confidence: 0.97, angle: 'left', x: 50, y: 250, width: 100, height: 80 }], capturedAt: '2024-07-18T14:08:00Z' },
      { angle: 'right', imageUrl: '/mock/right.jpg', resultUrl: '/mock/right-result.jpg', damages: [], capturedAt: '2024-07-18T14:11:00Z' },
    ],
    totalDamages: 2,
    notes: 'Ban kiri flat, perlu penggantian segera.',
    startedAt: '2024-07-18T13:55:00Z',
    completedAt: '2024-07-18T14:15:00Z',
    createdAt: '2024-07-18',
  },
  {
    id: 'ins-003',
    vehicleId: 'veh-011',
    licensePlate: 'L 1234 EFG',
    vehicleName: 'Hyundai Ioniq 6 2023',
    clientId: 'cli-003',
    clientName: 'UD. Kilat Express',
    inspectorName: 'Bagas Prasetyo',
    status: 'in_progress',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: '/mock/front-result.jpg', damages: [{ id: 'd7', type: 'glass_shatter', severity: 'high', confidence: 0.93, angle: 'front', x: 80, y: 50, width: 120, height: 60 }], capturedAt: '2024-07-20T10:30:00Z' },
      { angle: 'rear', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'left', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'right', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
    ],
    totalDamages: 1,
    notes: 'Proses inspeksi sedang berlangsung.',
    startedAt: '2024-07-20T10:25:00Z',
    completedAt: null,
    createdAt: '2024-07-20',
  },
  {
    id: 'ins-004',
    vehicleId: 'veh-009',
    licensePlate: 'H 3456 YZA',
    vehicleName: 'Toyota Kijang Innova 2021',
    clientId: 'cli-008',
    clientName: 'PT. Trans Nusa Cargo',
    inspectorName: 'Ahmad Rizki',
    status: 'completed',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: '/mock/front-result.jpg', damages: [], capturedAt: '2024-07-05T08:00:00Z' },
      { angle: 'rear', imageUrl: '/mock/rear.jpg', resultUrl: '/mock/rear-result.jpg', damages: [{ id: 'd8', type: 'lamp_broken', severity: 'medium', confidence: 0.91, angle: 'rear', x: 30, y: 40, width: 40, height: 30 }], capturedAt: '2024-07-05T08:05:00Z' },
      { angle: 'left', imageUrl: '/mock/left.jpg', resultUrl: '/mock/left-result.jpg', damages: [], capturedAt: '2024-07-05T08:08:00Z' },
      { angle: 'right', imageUrl: '/mock/right.jpg', resultUrl: '/mock/right-result.jpg', damages: [{ id: 'd9', type: 'scratch', severity: 'low', confidence: 0.75, angle: 'right', x: 200, y: 180, width: 40, height: 12 }], capturedAt: '2024-07-05T08:12:00Z' },
    ],
    totalDamages: 2,
    notes: 'Lampu belakang kanan rusak.',
    startedAt: '2024-07-05T07:55:00Z',
    completedAt: '2024-07-05T08:20:00Z',
    createdAt: '2024-07-05',
  },
  {
    id: 'ins-005',
    vehicleId: 'veh-004',
    licensePlate: 'L 3456 JKL',
    vehicleName: 'Mitsubishi Xpander 2023',
    clientId: 'cli-003',
    clientName: 'UD. Kilat Express',
    inspectorName: 'Sari Dewi',
    status: 'pending',
    angles: [
      { angle: 'front', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'rear', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'left', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'right', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
    ],
    totalDamages: 0,
    notes: 'Awaiting vehicle arrival at inspection facility.',
    startedAt: '2024-07-23T00:00:00Z',
    completedAt: null,
    createdAt: '2024-07-23',
  },
  {
    id: 'ins-006',
    vehicleId: 'veh-001',
    licensePlate: 'B 1234 ABC',
    vehicleName: 'Toyota Avanza 2022',
    clientId: 'cli-001',
    clientName: 'PT. Berkah Transportasi Nusantara',
    inspectorName: 'Bagas Prasetyo',
    status: 'completed',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: '/mock/front-result.jpg', damages: [{ id: 'd10', type: 'dent', severity: 'low', confidence: 0.82, angle: 'front', x: 180, y: 120, width: 30, height: 25 }], capturedAt: '2024-07-10T11:00:00Z' },
      { angle: 'rear', imageUrl: '/mock/rear.jpg', resultUrl: '/mock/rear-result.jpg', damages: [], capturedAt: '2024-07-10T11:05:00Z' },
      { angle: 'left', imageUrl: '/mock/left.jpg', resultUrl: '/mock/left-result.jpg', damages: [], capturedAt: '2024-07-10T11:08:00Z' },
      { angle: 'right', imageUrl: '/mock/right.jpg', resultUrl: '/mock/right-result.jpg', damages: [{ id: 'd11', type: 'scratch', severity: 'low', confidence: 0.80, angle: 'right', x: 100, y: 160, width: 35, height: 10 }], capturedAt: '2024-07-10T11:11:00Z' },
    ],
    totalDamages: 2,
    notes: 'Vehicle in good overall condition with minor scratches.',
    startedAt: '2024-07-10T10:55:00Z',
    completedAt: '2024-07-10T11:20:00Z',
    createdAt: '2024-07-10',
  },
  {
    id: 'ins-007',
    vehicleId: 'veh-010',
    licensePlate: 'B 7890 BCD',
    vehicleName: 'Suzuki Ignis 2023',
    clientId: 'cli-006',
    clientName: 'Blue Bird Taxi Unit 5',
    inspectorName: 'Ahmad Rizki',
    status: 'completed',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: '/mock/front-result.jpg', damages: [], capturedAt: '2024-07-12T09:00:00Z' },
      { angle: 'rear', imageUrl: '/mock/rear.jpg', resultUrl: '/mock/rear-result.jpg', damages: [{ id: 'd12', type: 'crack', severity: 'medium', confidence: 0.89, angle: 'rear', x: 140, y: 90, width: 60, height: 25 }], capturedAt: '2024-07-12T09:06:00Z' },
      { angle: 'left', imageUrl: '/mock/left.jpg', resultUrl: '/mock/left-result.jpg', damages: [], capturedAt: '2024-07-12T09:10:00Z' },
      { angle: 'right', imageUrl: '/mock/right.jpg', resultUrl: '/mock/right-result.jpg', damages: [], capturedAt: '2024-07-12T09:13:00Z' },
    ],
    totalDamages: 1,
    notes: '',
    startedAt: '2024-07-12T08:55:00Z',
    completedAt: '2024-07-12T09:20:00Z',
    createdAt: '2024-07-12',
  },
  {
    id: 'ins-008',
    vehicleId: 'veh-002',
    licensePlate: 'B 5678 DEF',
    vehicleName: 'Honda Brio 2023',
    clientId: 'cli-001',
    clientName: 'PT. Berkah Transportasi Nusantara',
    inspectorName: 'Sari Dewi',
    status: 'failed',
    angles: [
      { angle: 'front', imageUrl: '/mock/front.jpg', resultUrl: null, damages: [], capturedAt: '2024-07-15T13:00:00Z' },
      { angle: 'rear', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'left', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
      { angle: 'right', imageUrl: null, resultUrl: null, damages: [], capturedAt: null },
    ],
    totalDamages: 0,
    notes: 'AI service timed out during detection process. Retry required.',
    startedAt: '2024-07-15T12:55:00Z',
    completedAt: null,
    createdAt: '2024-07-15',
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalClients: {
    label: 'Total Clients',
    value: 8,
    change: 14.3,
    trend: [3, 4, 4, 5, 5, 6, 7, 8],
  },
  totalVehicles: {
    label: 'Total Vehicles',
    value: 47,
    change: 8.7,
    trend: [28, 32, 35, 37, 40, 42, 44, 47],
  },
  inspectionsThisMonth: {
    label: 'Inspections This Month',
    value: 24,
    change: 20.0,
    trend: [8, 10, 12, 14, 16, 18, 21, 24],
  },
  aiDetectionsThisMonth: {
    label: 'AI Detections',
    value: 87,
    change: 31.8,
    trend: [30, 38, 45, 52, 60, 68, 77, 87],
  },
};

// Weekly inspection trend for dashboard chart
export const weeklyInspectionData = [
  { day: 'Mon', inspections: 4, detections: 12 },
  { day: 'Tue', inspections: 6, detections: 19 },
  { day: 'Wed', inspections: 5, detections: 15 },
  { day: 'Thu', inspections: 8, detections: 26 },
  { day: 'Fri', inspections: 7, detections: 22 },
  { day: 'Sat', inspections: 3, detections: 9 },
  { day: 'Sun', inspections: 2, detections: 6 },
];

// Monthly trend for area chart
export const monthlyTrendData = [
  { month: 'Jan', value: 12 },
  { month: 'Feb', value: 18 },
  { month: 'Mar', value: 15 },
  { month: 'Apr', value: 22 },
  { month: 'May', value: 28 },
  { month: 'Jun', value: 25 },
  { month: 'Jul', value: 35 },
  { month: 'Aug', value: 40 },
];

// Damage type distribution for donut chart
export const damageDistribution = [
  { type: 'Scratch', key: 'scratch', value: 34, color: '#f59e0b' },
  { type: 'Dent',  key: 'dent',    value: 28, color: '#6366f1' },
  { type: 'Crack',   key: 'crack',   value: 16, color: '#ef4444' },
  { type: 'Glass Shatter',    key: 'glass_shatter', value: 10, color: '#8b5cf6' },
  { type: 'Broken Light',   key: 'lamp_broken',   value: 8,  color: '#f97316' },
  { type: 'Flat Tire',     key: 'tire_flat',     value: 4,  color: '#06b6d4' },
];
